name: Build Docker Base Image

on:
  push:
    branches: ["main"]
    paths:
      - 'Dockerfile.builder'
      - 'Dockerfile.runtime'
      - 'install_dependencies.sh'
      - '.github/workflows/build-base-image.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # 定义构建镜像的通用模板
  build-image:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    strategy:
      fail-fast: false  # 一个构建失败不影响另一个
      matrix:
        image-type: [runtime, builder]  # 并行构建两种镜像
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ${{ matrix.image-type }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.${{ matrix.image-type }}
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/xiaomusic:${{ matrix.image-type }}
